// JavaScript goes here.
let pono = document.querySelector("#pono");
let mana = document.querySelector("#mana");
let ohana = document.querySelector("#ohana");
let aloha = document.querySelector("#aloha");
let calm = document.querySelector("#calm");
let hurt = document.querySelector("#hurt");
let bite = document.querySelector("#bite");
let laugh = document.querySelector("#laugh");
let momFriend = document.querySelector("#mom-friend");
let joker = document.querySelector("#joker");
let wildCard = document.querySelector("#wild-card");
let fixer = document.querySelector("#fixer");
let jumba = document.querySelector("#jumba");
let lilo = document.querySelector("#lilo");
let pleakley = document.querySelector("#pleakley");
let stitch = document.querySelector("#stitch");
let weird = document.querySelector("#weird");
let careless = document.querySelector("#careless");
let trying = document.querySelector("#trying");
let wild = document.querySelector("#wild");
let calmDown = document.querySelector("#calm-down");
let ignored = document.querySelector("#ignored");
let routines = document.querySelector("#routines");
let changePlans = document.querySelector("#change-plans");
let empathy = document.querySelector("#empathy");
let loyalty = document.querySelector("#loyalty");
let creativity = document.querySelector("#creativity");
let resilience = document.querySelector("#resilience");


